### ISSUE TITLE
После настройки аддона: Internal Server Error 

### ISSUE THREAD

**Issue by SAMaksimov** [maxifly/YaBackupAddon#1]
Введены все данные, открываю вебуи аддона, всё ок, получаю токен и ввожу, после этого ошибка

Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by maxifly** [comment]
Если да, вот у меня тоже самое.
Неожиданно прямо. Опять в Яндексе поменяли что-то. Ну вот что за ерунда.

**Comment by maxifly** [comment]
```
[2023-09-22 13:12:52,753] DEBUG in yad: Try get token from YaDisk
[2023-09-22 13:12:52,934] DEBUG in yad: Try save token
[2023-09-22 13:12:52,934] DEBUG in yad: New token expires in 2024-09-21 13:03:32.934231
[2023-09-22 13:12:52,935] INFO in _internal: 172.30.32.2 - - [22/Sep/2023 13:12:52] "POST /get_token HTTP/1.1" 302 -
[2023-09-22 13:12:52,946] INFO in yabackup: Root request
[2023-09-22 13:12:52,946] DEBUG in yabackup: Prefix: /api/hassio_ingress/S5PY8lxbJByBYLAwwxUWAFLqYR0Ya5ZxQ-kSo7l87So
[2023-09-22 13:12:53,399] ERROR in yad: Error get directory info. Path: /ha_test
Traceback (most recent call last):
  File "/app/yad.py", line 208, in _list_yandex_disk
    files = self._file_list_processing(y.listdir(self._path))
  File "/app/yad.py", line 305, in _file_list_processing
    files = [obj for obj in objects if obj.type == TYPE_FILE]
  File "/app/yad.py", line 305, in <listcomp>
    files = [obj for obj in objects if obj.type == TYPE_FILE]
  File "/usr/lib/python3.8/site-packages/yadisk/yadisk.py", line 75, in _listdir
    result = get_meta_function(path, **kwargs)
  File "/usr/lib/python3.8/site-packages/yadisk/yadisk.py", line 443, in get_meta
    request.send()
  File "/usr/lib/python3.8/site-packages/yadisk/api/api_request.py", line 124, in send
    auto_retry(self._attempt, self.n_retries, self.retry_interval)
  File "/usr/lib/python3.8/site-packages/yadisk/utils.py", line 96, in auto_retry
    return func()
  File "/usr/lib/python3.8/site-packages/yadisk/api/api_request.py", line 115, in _attempt
    raise get_exception(self.response)
yadisk.exceptions.ForbiddenError: Доступ запрещён. Возможно, у приложения недостаточно прав для данного действия. (Forbidden / ForbiddenError)
[2023-09-22 13:12:53,401] DEBUG in bkp_observer: Check /backup path
```

Я попробовал новое приложение зарегистрировать и к нему токен получить.
Я вот точно помню, что когда регистрируешь приложение, то нужно выбрать, что ему даются права на доступ к диску. Теперь эти права из списка прав при регистрации нового приложения делись куда-то.

И по логу видно, что токен приходит, но у него нет прав на доступ к диску.

**Comment by maxifly** [comment]
Я проверил. У меня заработало. Единственно, что я так понимаю вам надо будет аддон удалить и заново поставить, чтобы токен без прав удалился.

**Comment by maxifly** [comment]
Пойду поправлю доку.

**Comment by maxifly** [comment]
@SAMaksimov 
Пока баг я оставлю открытым. Отпишитесь, если возможно,  помогли вам рекомендации или нет.

**Comment by MitekV** [comment]
не может установить дополнение.  неизвестная ошибка

**Comment by maxifly** [comment]
Ответа нет. Баг закрываю.
